const Sequelize = require("sequelize");
module.exports = function (sequelize, DataTypes) {
  return sequelize.define(
    "SysMenu",
    {
      menuId: {
        autoIncrement: true,
        type: DataTypes.BIGINT,
        allowNull: false,
        primaryKey: true,
        comment: "菜单ID",
        field: "menu_id",
      },
      menuName: {
        type: DataTypes.STRING(50),
        allowNull: false,
        comment: "菜单名称",
        field: "menu_name",
      },
      parentId: {
        type: DataTypes.BIGINT,
        allowNull: true,
        defaultValue: 0,
        comment: "父菜单ID",
        field: "parent_id",
      },
      orderNum: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 0,
        comment: "显示顺序",
        field: "order_num",
      },
      path: {
        type: DataTypes.STRING(200),
        allowNull: true,
        defaultValue: "",
        comment: "路由地址",
      },
      component: {
        type: DataTypes.STRING(255),
        allowNull: true,
        comment: "组件路径",
      },
      query: {
        type: DataTypes.STRING(255),
        allowNull: true,
        comment: "路由参数",
      },
      routeName: {
        type: DataTypes.STRING(50),
        allowNull: true,
        defaultValue: "",
        comment: "路由名称",
        field: "route_name",
      },
      isFrame: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 1,
        comment: "是否为外链（0是 1否）",
        field: "is_frame",
      },
      isCache: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 0,
        comment: "是否缓存（0缓存 1不缓存）",
        field: "is_cache",
      },
      menuType: {
        type: DataTypes.CHAR(1),
        allowNull: true,
        defaultValue: "",
        comment: "菜单类型（M目录 C菜单 F按钮）",
        field: "menu_type",
      },
      visible: {
        type: DataTypes.CHAR(1),
        allowNull: true,
        defaultValue: "0",
        comment: "菜单状态（0显示 1隐藏）",
      },
      status: {
        type: DataTypes.CHAR(1),
        allowNull: true,
        defaultValue: "0",
        comment: "菜单状态（0正常 1停用）",
      },
      perms: {
        type: DataTypes.STRING(100),
        allowNull: true,
        comment: "权限标识",
      },
      icon: {
        type: DataTypes.STRING(100),
        allowNull: true,
        defaultValue: "#",
        comment: "菜单图标",
      },
      createBy: {
        type: DataTypes.STRING(64),
        allowNull: true,
        defaultValue: "",
        comment: "创建者",
        field: "create_by",
      },
      createTime: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "创建时间",
        field: "create_time",
      },
      updateBy: {
        type: DataTypes.STRING(64),
        allowNull: true,
        defaultValue: "",
        comment: "更新者",
        field: "update_by",
      },
      updateTime: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "更新时间",
        field: "update_time",
      },
      remark: {
        type: DataTypes.STRING(500),
        allowNull: true,
        defaultValue: "",
        comment: "备注",
      },
    },
    {
      tableName: "sys_menu",
      timestamps: true,
      createdAt: "createTime",
      updatedAt: "updateTime",
      underscored: true,
      freezeTableName: true,
      comment: true,
      indexes: [
        {
          name: "PRIMARY",
          unique: true,
          using: "BTREE",
          fields: [{ name: "menu_id" }],
        },
      ],
    },
  );
};
