const Sequelize = require("sequelize");
module.exports = function (sequelize, DataTypes) {
  return sequelize.define(
    "SysUser",
    {
      userId: {
        autoIncrement: true,
        type: DataTypes.BIGINT,
        allowNull: false,
        primaryKey: true,
        comment: "用户ID",
        field: "user_id",
      },
      deptId: {
        type: DataTypes.BIGINT,
        allowNull: true,
        comment: "部门ID",
        field: "dept_id",
      },
      userName: {
        type: DataTypes.STRING(30),
        allowNull: false,
        comment: "用户账号",
        field: "user_name",
      },
      nickName: {
        type: DataTypes.STRING(30),
        allowNull: false,
        comment: "用户昵称",
        field: "nick_name",
      },
      userType: {
        type: DataTypes.STRING(2),
        allowNull: true,
        defaultValue: "00",
        comment: "用户类型（00系统用户）",
        field: "user_type",
      },
      email: {
        type: DataTypes.STRING(50),
        allowNull: true,
        defaultValue: "",
        comment: "用户邮箱",
      },
      phonenumber: {
        type: DataTypes.STRING(11),
        allowNull: true,
        defaultValue: "",
        comment: "手机号码",
      },
      sex: {
        type: DataTypes.CHAR(1),
        allowNull: true,
        defaultValue: "0",
        comment: "用户性别（0男 1女 2未知）",
      },
      avatar: {
        type: DataTypes.STRING(100),
        allowNull: true,
        defaultValue: "",
        comment: "头像地址",
      },
      password: {
        type: DataTypes.STRING(100),
        allowNull: true,
        defaultValue: "",
        comment: "密码",
      },
      status: {
        type: DataTypes.CHAR(1),
        allowNull: true,
        defaultValue: "0",
        comment: "帐号状态（0正常 1停用）",
      },
      delFlag: {
        type: DataTypes.CHAR(1),
        allowNull: true,
        defaultValue: "0",
        comment: "删除标志（0代表存在 2代表删除）",
        field: "del_flag",
      },
      loginIp: {
        type: DataTypes.STRING(128),
        allowNull: true,
        defaultValue: "",
        comment: "最后登录IP",
        field: "login_ip",
      },
      loginDate: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "最后登录时间",
        field: "login_date",
      },
      createBy: {
        type: DataTypes.STRING(64),
        allowNull: true,
        defaultValue: "",
        comment: "创建者",
        field: "create_by",
      },
      createTime: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "创建时间",
        field: "create_time",
      },
      updateBy: {
        type: DataTypes.STRING(64),
        allowNull: true,
        defaultValue: "",
        comment: "更新者",
        field: "update_by",
      },
      updateTime: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "更新时间",
        field: "update_time",
      },
      remark: {
        type: DataTypes.STRING(500),
        allowNull: true,
        comment: "备注",
      },
    },
    {
      tableName: "sys_user",
      timestamps: true,
      createdAt: "createTime",
      updatedAt: "updateTime",
      underscored: true,
      freezeTableName: true,
      comment: true,
      indexes: [
        {
          name: "PRIMARY",
          unique: true,
          using: "BTREE",
          fields: [{ name: "user_id" }],
        },
      ],
    },
  );
};
